# Generated by Django 3.0.2 on 2020-01-27 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='loggedIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'loggedIn',
            },
        ),
        migrations.CreateModel(
            name='notLoggedIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'notLoggedIn',
            },
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('loggedIn', models.ManyToManyField(to='api.loggedIn')),
                ('notLoggedIn', models.ManyToManyField(to='api.notLoggedIn')),
            ],
            options={
                'verbose_name_plural': 'users',
            },
        ),
    ]
