# Generated by Django 3.0.2 on 2020-01-27 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='users',
            name='loggedIn',
        ),
        migrations.RemoveField(
            model_name='users',
            name='notLoggedIn',
        ),
        migrations.DeleteModel(
            name='loggedIn',
        ),
        migrations.DeleteModel(
            name='notLoggedIn',
        ),
    ]
